blog/urls.py
"""
Urls of the blog application
"""
from blog.views import about_us, get_view_factory
from django.urls import path

post_list = get_view_factory('PostsListFactory').create()
post_detail = get_view_factory('PostsDetailFactory').create()
contact_us = get_view_factory('ContactFactory').create()
about_us = get_view_factory('AboutUsFactory').create()
algorithms_list = get_view_factory('PostListAlgorithmsFactory').create()
mathematics_list = get_view_factory('PostListMathematicsFactory').create()
post_list = get_view_factory('PostsListFactory').create()
post_detail = get_view_factory('PostsDetailFactory').create()
contact_us = get_view_factory('ContactFactory').create()
algorithms_list = get_view_factory('PostListAlgorithmsFactory').create()
mathematics_list = get_view_factory('PostListMathematicsFactory').create()


urlpatterns = [
    path('', post_list.as_view(), name='home'),
    path('contact/', contact_us.as_view(), name='contact'),
    path('algorithms/', algorithms_list.as_view(), name='algorithms'),
    path('mathematics/', mathematics_list.as_view(), name='mathematics'),
    path('aboutus/', about_us.as_view(), name='aboutus'),
    path('<slug:slug>/', post_detail.as_view(), name='post_detail'),
]

education4all/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('blog.urls')),
]

blog/models/models_factory.py
"""
Implements a factory for view classes
"""
from abc import ABC, abstractmethod
from .posts import PostModel


class ModelsFactory(ABC):
    """
    Generates models objects
    """
    @abstractmethod
    def create(self):
        """
        Create the object
        """


class PostsFactory(ModelsFactory):
    """
    Generates the object responsible for store posts in the database
    """
    def create(self):
        """
        Create the PostModel object
        """
        return PostModel


def get_model_factory(name):
    """
    Get the correspondent models factory:

        Args:
            name: name of the factory, it can be:
                  'PostsFactory'
    """
    factory_map = {'PostsFactory': PostsFactory()}

    try:
        return factory_map[name]
    except KeyError as key_error:
        raise Exception('Name parameter not in the options') from key_error

blog/models/posts.py
"""
Database model for posts
"""
from django.db import models
from django.contrib.auth.models import User




class PostModel(models.Model):
    """
    Class representing the post model in the database
    """
    STATUS = (
    (0,"Draft"),
    (1,"Publish")
    )
    SECTION = (
        (0, "Matemática"),
        (1, "Algoritmos"),
    )
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    section = models.IntegerField(choices=SECTION, default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        """
        Posts model metadata
        """
        ordering = ['-created_on']

    def __str__(self):
        """
        Returns a char field for the model
        """
        return str(self.title)

blog/views/about_us.py
"""
about us page
"""
from django.views import generic


class AboutUs(generic.TemplateView):
    """
    Shows contact us page
    """
    template_name = 'about_us.html'

blog/views/contact.py
"""
contact us page
"""
from django.views import generic


class ContactUs(generic.TemplateView):
    """
    Shows contact us page
    """
    template_name = 'contact.html'

blog/views/posts.py
"""
View for posts model
"""
from django.views import generic
from blog.models import get_model_factory


class PostList(generic.ListView):
    """
    Create a list of posts ordered by most recent
    """
    model = get_model_factory('PostsFactory').create()
    queryset = model.objects.filter(status=1).order_by('-created_on')[:10]
    template_name = 'index.html'


class PostListAlgorithms(generic.ListView):
    """
    Create a list of posts ordered by most recent
    """
    model = get_model_factory('PostsFactory').create()
    queryset = model.objects.filter(status=1,
                                    section=1).order_by('-created_on')[:10]
    template_name = 'sections.html'


class PostListMathematics(generic.ListView):
    """
    Create a list of posts ordered by most recent
    """
    model = get_model_factory('PostsFactory').create()
    queryset = model.objects.filter(status=1,
                                    section=0).order_by('-created_on')[:10]

    template_name = 'sections.html'


class PostDetail(generic.DetailView):
    """
    Shows details for a specific post
    """
    model = get_model_factory('PostsFactory').create()
    template_name = 'post_detail.html'

blog/views/views_factory.py
"""
Implements a factory for view classes
"""
from abc import ABC, abstractmethod
from blog.views.about_us import AboutUs
from .posts import PostDetail, PostList, PostListAlgorithms, PostListMathematics
from .contact import ContactUs
from .about_us import AboutUs


class ViewsFactory(ABC):
    """
    Generates view objects
    """
    @abstractmethod
    def create(self):
        """
        Create the object
        """


class PostsDetailFactory(ViewsFactory):
    """
    Generates the object responsible for post details creation
    """
    def create(self):
        """
        Create the PostDetail object
        """
        return PostDetail


class PostsListFactory(ViewsFactory):
    """
    Generates the object responsible for list the posts
    """
    def create(self):
        """
        Create the PostList object
        """
        return PostList


class PostListAlgorithmsFactory(ViewsFactory):
    """
    Generates the object responsible for list the posts about algorithms
    """
    def create(self):
        """
        Create the PostList object
        """
        return PostListAlgorithms


class PostListMathematicsFactory(ViewsFactory):
    """
    Generates the object responsible for list the posts about algorithms
    """
    def create(self):
        """
        Create the PostList object
        """
        return PostListMathematics


class ContactFactory(ViewsFactory):
    """
    Generates the object responsible for show contact informations
    """
    def create(self):
        """
        Create the Contact us object
        """
        return ContactUs


class AboutUsFactory(ViewsFactory):
    """
    Generates the object responsible for show informations about ourselves
    """
    def create(self):
        """
        Create the About us object
        """
        return AboutUs


def get_view_factory(name):
    """
    Get the correspondent view factory:

        Args:
            name: name of the factory, it can be:
                  'ContactFactory'
                  'PostsListFactory'
                  'PostsDetailFactory'
    """
    factory_map = {
        'ContactFactory': ContactFactory(),
        'PostsListFactory': PostsListFactory(),
        'PostsDetailFactory': PostsDetailFactory(),
        'PostListAlgorithmsFactory': PostListAlgorithmsFactory(),
        'PostListMathematicsFactory': PostListMathematicsFactory(),
        'AboutUsFactory': AboutUsFactory(),
    }

    try:
        return factory_map[name]
    except KeyError as key_error:
        raise Exception('Name parameter not in the options') from key_error

templates/about_us.html
{% extends "base.html" %}
{% block content %}
<style>
    .card-img-top {
        width: 100%;
        height: 350px;
        object-fit: cover;
    }
</style>

<!-- Page header-->
<header class="Homeheader"
    style="background-image: url('https://images.freeimages.com/images/large-previews/e77/math-1182795.jpg')">
    <div class="container-fluid position-relative px-0 px-lg-0 mx">
        <div class="row gy-1 gy-lg-1 justify-content-center">
            <div class="col-md-8 col-lg-8 col-xl-7">
                <!--<div class="site-heading">
                    <h1 class="h1HomeHeader">Education4all</h1>
                    <span class="subheading">Um lugar onde impulsionamos o conhecimento</span>
                </div> -->
            </div>
        </div>
    </div>
</header>
<div class="container">

    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-12 col-md-8 col-xl-4  text-center d-flex mx-auto">
            <div class="card mb-4 flex-fill">
                <img src="https://images.freeimages.com/images/large-previews/595/law-education-series-3-1467430.jpg"
                    class="card-img-top" alt="Question Mark">
                <div class="card-body">
                    <h1 class="card-title">O que é Education4all?</h1>
                    <p class="card-text">
                        Education4all é um projeto sem fins lucrativos desenvolvido como projeto da disciplina CES-22
                        (Introdução à programação orientada a objetos)
                        ministrada no Instituto Tecnológico de Aeronáutica.
                    </p>

                </div>
            </div>

        </div>


        <div class="col-12 col-md-8 col-xl-4  text-center d-flex mx-auto">
            <div class="card mb-4 flex-fill">
                <img src="https://images.freeimages.com/images/large-previews/2aa/on-target-1504936.jpg"
                    class="card-img-top" alt="Question Mark">
                <div class="card-body">
                    <h1 class="card-title">Qual o nosso objetivo?</h1>
                    <p class="card-text">
                        Nosso principal objetivo é disponibilizar material de alto nível disponibilizado em português
                        para
                        estudantes brasileiros. Nosso site disponibiliza artigos relevantes à duas áreas do
                        conhecimento: Algoritmos e Matemática.
                        A maioria dos artigos trazem explicações de conceitos complexos ou resoluções de problemas
                        populares.
                    </p>
                </div>
            </div>

        </div>


        <div class="col-12 col-md-8 col-xl-4  text-center d-flex mx-auto">
            <div class="card mb-4 flex-fill">
                <img src="https://images.freeimages.com/images/large-previews/f3f/foosball-table-soccer-1532452.jpg"
                    class="card-img-top" alt="Question Mark">
                <div class="card-body">
                    <h1 class="card-title">Sobre a equipe</h1>
                    <p class="card-text">
                        A equipe é composta por seis graduandos em Engenharia da Computação. Cada um deles tem hobbies
                        pessoais
                        distintos. No entanto, eles compartilham algo em comum: a sede por aprendizado e por
                        compartilhar o que sabem!!
                    </p>
                </div>
            </div>

        </div>

    </div>
</div>
{%endblock%}

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>Education4all</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--Jquery script-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!--Bootstrap Js and CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!--Montserrat font-->
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>

<style>
    body {
        font-family: "Montserrat", sans-serif;
    }

    .shadow {
        box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
    }

    .btn-danger {
        color: #fff;
        background-color: #f00000;
        border-color: #dc281e;
    }

    .masthead {
        background: #3398E1;
        height: auto;
        padding-bottom: 15px;
        box-shadow: 0 16px 48px #E3E7EB;
        padding-top: 10px;
    }

    .jumbotron {
        margin-bottom: 0px;
    }



    .Homeheader{
        position: relative;
    margin-bottom: 3rem;
    padding-top: calc(8rem + 57px);
    padding-bottom: 8rem;

    background: no-repeat center center;
    background-color: gray;
    background-size: cover;
    background-attachment: scroll;
    
    }

    .Homeheader::before{
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: white;
        opacity: 0.1;
    }

    .Homeheader .h1HomeHeader{
    font-size: 3rem;
    color: black ;
    font-weight: 900;
    
    }


    .Homeheader .subheading{
        font-size: 1.5rem;
            font-weight: 300;
            line-height: 1.1;
            display: block;
            margin-top: 0.625rem;
            color:black;
    
    }

</style>


<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light " id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" style="font-weight: bolder;" href="{% url 'home'%}">Education4all</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" style="font-weight: bolder;"
                            href="{% url 'home'%}">Home</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" style="font-weight: bolder;"
                            href="{% url 'aboutus'%}">Sobre Nós</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" style="font-weight: bolder;"

                            href="{% url 'algorithms'%}">Algoritmos</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" style="font-weight: bolder;"
                            href="{% url 'mathematics'%}">Matemática</a></li>
                            

                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" style="font-weight: bolder;"
                            href="{% url 'contact'%}">Contato</a></li>
                </ul>
            </div>
        </div>
    </nav>


    {% block content %}
    <!-- Content Goes here -->
    {% endblock content %}
    <!-- Footer -->
    <footer class="py-3 bg-grey">
        <p class="m-0 text-dark text-center ">Copyright &copy; Education4all</p>
    </footer>
</body>

</html>

templates/contact.html
{% extends "base.html" %}
{% block content %}
<style>
    .postsHeader {
        font-size: 2rem;
        font-weight: 900;
    }
</style>

<!-- Page header-->
<header class="Homeheader"
    style="background-image: url('https://images.freeimages.com/images/large-previews/e77/math-1182795.jpg')">
    <div class="container-fluid position-relative px-0 px-lg-0">
        <div class="row gy-1 gy-lg-1 justify-content-center">
            <div class="col-md-8 col-lg-8 col-xl-7">
                <!--<div class="site-heading">
                    <h1 class="h1HomeHeader">Education4all</h1>
                    <span class="subheading">Um lugar onde impulsionamos o conhecimento</span>
                </div> -->
            </div>
        </div>
    </div>
</header>
<div class="container">

    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-10 col-md-8 col-xl-6  text-center mx-auto">
            <div class="card mb-4 ">
                <img src="https://images.freeimages.com/images/large-previews/356/what-s-that-1527433.jpg" class="card-img-top"
                    alt="Question Mark">
                <div class="card-body">
                    <h1 class="card-title">Tem perguntas? Nós temos respostas!!</h1>
                    <address class="card-text">
                        Caso queira nos contatar, utilize esse <a href="mailto:education4all@gmail.com">email</a>
                        para nos contatar sobre qualquer sugestão ou bug reportado.
                    </address>
                    <address class="card-text">
                        Informamos que não aceitamos sugestões comerciais ou de propagandas, o conteúdo dos emails devem ser
                        extritamente
                        sobre o conteúdo do site. Para dúvidas, utilize a seção de comentários em cada post.
                    </address>
                    </div>
            </div>
            
            </div>

    </div>
</div>
{%endblock%}

templates/index.html
{% extends 'base.html' %}
{% block content %}
{% load markdown_extras %}
<script>
MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  },
  svg: {
    fontCache: 'global'
  }
};
</script>

<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js">
</script>
<style>
    .postsHeader{
        font-size: 2rem;
        font-weight: 900;
    }

</style>

<!-- Page header-->
<header class="Homeheader"
    style="background-image: url('https://miro.medium.com/max/3840/1*OOWSoWHeQ5kyJ4N0P2ptNA.png')">
    <div class="container-fluid position-relative px-0 px-lg-0">
        <div class="row gy-1 gy-lg-1 justify-content-center">
            <div class="col-md-8 col-lg-8 col-xl-7">
                <!--<div class="site-heading">
                    <h1 class="h1HomeHeader">Education4all</h1>
                    <span class="subheading">Um lugar onde impulsionamos o conhecimento</span>
                </div> -->
            </div>
        </div>
    </div>
</header>
<div class="container">


    <h1 class="postsHeader">Posts mais recentes</h1>


    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in postmodel_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text ">{{ post.content | slice:":200" | markdown | safe}}</p>
                    <p class="text-primary">{{ post.get_section_display }}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Ler mais &rarr;</a>

                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{%endblock%}

templates/post_detail.html
{% extends 'base.html' %} {% block content %}
{% load markdown_extras %}

<script>
MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  },
  svg: {
    fontCache: 'global'
  }
};
</script>
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js">
</script>

{% load markdown_extras %}

<script>
MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  },
  svg: {
    fontCache: 'global'
  }
};
</script>
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js">
</script>

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ object.author }} | {{ object.created_on }}</p>
        <p class="card-text ">{{ object.content | markdown | safe }}</p>
        <p class="text-primary">{{ object.get_section_display }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
  </div>
</div>

{% endblock content %}

templates/sections.html
{% extends 'base.html' %}
{% block content %}
{% load markdown_extras %}
<script>
    MathJax = {
        tex: {
            inlineMath: [['$', '$'], ['\\(', '\\)']]
        },
        svg: {
            fontCache: 'global'
        }
    };
</script>

<script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js">
</script>
<style>
    .postsHeader {
        font-weight: 900;
    }
</style>

<!-- Page header-->
<header class="Homeheader"
    style="background-image: url('https://images.freeimages.com/images/large-previews/e77/math-1182795.jpg')">
    <div class="container-fluid position-relative px-0 px-lg-0">
        <div class="row gy-1 gy-lg-1 justify-content-center">
            <div class="col-md-8 col-lg-8 col-xl-7">
            </div>
        </div>
    </div>
</header>-
<header></header>
<div class="container">





    <div class="row">
        <h1 class="col-md-8 mx-auto text-center mb-5 postsHeader">Posts mais recentes</h1>
        <!-- Blog Entries Column -->
        <div class="col-md-8 mx-auto left">
            {% for post in postmodel_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text ">{{ post.content | slice:":200" | markdown | safe}}</p>
                    <p class="text-primary">{{ post.get_section_display }}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Ler mais &rarr;</a>

                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{%endblock%}

templates/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
       
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">

        <h5 class="card-header">Sobre nós</h5>
    <div class="card-body">
        <p class="card-text"> Esse é um blog que objetiva compartilhar conhecimento gratuito para universitários brasileiros!
        </p>
        <a href="{% url 'aboutus'%}" class="btn btn-danger">Saiba mais!</a>
    </div>
</div>
</div>

{% endblock sidebar %}